### ISSUE TITLE
Create option to make REST client autologin and autorefresh tokens

### ISSUE THREAD

**Issue by runnane** [runnane/node-red-contrib-easee#13]
Create option to make REST client autologin and autorefresh tokens
* Should it be possible to disable?
* Auto login
* Auto refresh
* Auto back-off if X failed logins. 
* Use 3rd party oauth client or roll our own?

**Comment by I-am-a-node** [comment]
I know this is a year old and some of it already exists. However thought I would answer if some is still thought off. So please apologise if I am a bit behind on this.

**Q: Should it be possible to disable?**
**A**: I think it is down to how the two nodes should be used together or separated. I don't know how the backend is designed to work but my understanding is that you let the STREAM node handled this keeping you connected. I don't see why anyone would use the REST only? However if you do not wish to have "live' updates you can might want to be able not to add the stream node and only use the REST node and trigger your own token request.
**Q: Auto login**
**A**: You kind of can do an "Auto Login" today with the inject or cron node.
**Q: Auto Refresh**
**A:** Don't know. That there is kind of avail already?
**Q: Auto back-off if X failed login**
**A:** Yes could be good. Needs to be thought through. I do think it's more a priority to deal with failed Token renewals.
**Q: Use 3rd party auth client or roll you own.**
**A:** Also would be a nice option that you will be more in control. However maybe not a priority. It is a nice thing to have. If the Stream and REST nodes work fine with each other you would be great with a "backup" to when a login or authorisation fails. Now there is no way of catching this. An option to trigger a login with the REST node will bring the STREAM back on track.

**Comment by runnane** [comment]
Implemented in 0.5.8
