### ISSUE TITLE
Dynamic Currents always 0 after changing by predefined command and usage msg.payload.body

### ISSUE THREAD

**Issue by Realf0rce** [runnane/node-red-contrib-easee#17]
If i use an inject node as it is used in the examples for input for setting the dynamicCurrents.

The currents are always set to 0, regardless of the transmitted value. 
I am not sure how the values have to be transferred to the REST node. I tried it with the following parameters in the msg.payload.body,
Type String: {
     "phase1": 16.2,
     "phase2": 15.9,
     "phase3": 0.5,
     "timeToLive": 1
}
Type Object:
{
     "phase1": 16.2,
     "phase2": 15.9,
     "phase3": 0.5,
     "timeToLive": 1
}

but no success.

**Comment by nordlings** [comment]
This is how I define my payload in a function node and this works.
I use 2min TTL, and I control the charger once every minute.

msg.payload = {
    "path": "/sites/xxxxx/circuits/yyyyy/dynamicCurrent",
        "body": {
            "phase1": l1,
            "phase2": l2,
            "phase3": l3,
            "timeToLive": 2
    }
}

**Comment by Rea1force** [comment]
Hello Nordlinge
Thanks for the clarification.
It works fine for me too.

**Comment by nordlings** [comment]
Hey, you're welcome :)
But I think you might be right that the examples found in the docs are not
100% correct.
I had to try a few things before I figured it out...


Den mån 11 mars 2024 kl 23:05 skrev Rea1force ***@***.***>:

**Comment by Rea1force** [comment]
Works fine, 
Thanks

**Comment by Rea1force** [comment]
Unfortunately, this solution with the function no longer works since the last update to version 0.6.1. The Rest API no longer recognises that there is a body and only executes the GET function.
The transfer with the PPP executes a POST, but again with the result that all currents are 0.
Can you please support again?

**Comment by runnane** [comment]
Hi
Yeah, i see that this is a breaking change. I've added a workaround, verified that this works again:

```javascript
{
    "path": "/sites/yyy/circuits/xxx/dynamicCurrent",
    "body": {
        "phase1": 32,
        "phase2": 32,
        "phase3": 32
    }
}
```
