### ISSUE TITLE
Add support for DELETE/PUT commands

### ISSUE THREAD

**Issue by runnane** [runnane/node-red-contrib-easee#18]
Add support for DELETE/PUT commands in REST client, as mentioned in #17

**Comment by I-am-a-node** [comment]
Hi, do you refer to having the "functions" Delete and PUT as a "predefined commands by topic"? There are several things mentioned in that flow so... trying to understand exactly what you are referring to.

I use the custom commands and it works fine. However it took a while for me to get it right as it wasn't as easy as the document said. So one way could be if we can help out to update the instructions? Make the descriptions more clear to help others. However predefined are more helpful for the ones who aren't use to the payload structures and making function nodes with the correct msg forwards. Less issues and errors. Might make the node more attractive for others. Nice if more choose to use this node as it's such a good tool.

**Comment by KIDNORswe** [comment]
So does this just add more functionality to the REST node? Like with the HTTPS node? Not only GET and POST but also DELETE and PUT? Have I got it right?
