### ISSUE TITLE
Unexpected syntax error message flood: "SyntaxError: Unexpected token T in JSON at position 0"

### ISSUE THREAD

**Issue by RKausS** [runnane/node-red-contrib-easee#21]
Hello Jon
I'm new with your contribution.It works, but almost every day a flood of error messages suddenly appear out of nowhere (every few seconds two error messages):

**SyntaxError: Unexpected token T in JSON at position 0**

![Screenshot_1](https://github.com/runnane/node-red-contrib-easee/assets/3432018/24830e1f-9db6-464b-9835-6151726294be)

To narrow down the node causing the problem, I deleted one node after the other until they were all gone, but the error messages continued to appear until I deleted the corresponding configuration node.

If I query the status of the Node-RED service on the SSH shell, these error messages appear there too. Restarting the Node-RED service solves the problem too - for a few hours, or at best a day or two.

![Screenshot_2](https://github.com/runnane/node-red-contrib-easee/assets/3432018/4f72a9d7-335a-44c6-8baa-4266b4e92c43)

Due to my lack of experience with Node-RED, I cannot judge whether I am causing the problem myself? The fact that a restart solves the problem for some time also makes a problem with the contribution possible, right?

Kind regards
Roman

**Comment by runnane** [comment]
This is probably due to failed rest call not returning JSON.
Will make a check for this and output more descriptive error.

**Comment by runnane** [comment]
I've released 0.5.8 with some more informative error messages, please let me know what errors you get now, @RKausS

**Comment by runnane** [comment]
Assuming fixed
