### ISSUE TITLE
Cannot trigger POST for dynamicCurrent

### ISSUE THREAD

**Issue by EskildPa** [runnane/node-red-contrib-easee#23]
@runnane 
I will set dynamicCurrent, but cannot make this work. On [easee developer](https://developer.easee.com/reference/post_api-sites-siteid-circuits-circuitid-dynamiccurrent ) I can set it as desired, but not in the 'easee REST Client'.
Tried several  variants, but it is always resulting in a GET.
As read in another issue, I am using a function node like this to make the message:
```javascript
let l1 = 7;
let l2 = 0;
let l3 = 0;
msg.topic = "dynamic_current"
msg.payload = {
    "path": "/sites/1111/circuits/2222/dynamicCurrent",
    "body": {
            "phase1": l1,
            "phase2": l2,
            "phase3": l3,
                 }
     }
return msg;

``` 

Also tried without setting the topic.

debug to REST Client:
```shell
23.7.2024, 21:16:27node: debug 6
dynamic_current : msg : Object
object
_msgid: "eab0ebabb9827e8e"
    payload: object
    path: "/sites/1111/circuits/2222/dynamicCurrent"
    body: object
        phase1: 7
        phase2: 0
        phase3: 0
    topic: "dynamic_current"
``` 

debug from REST Client:
```shell
23.7.2024, 21:16:27node: debug 7
/sites/1111/circuits/2222/dynamicCurrent : msg : Object
object
    status: "ok"
    topic: "/sites/1111/circuits/2222/dynamicCurrent"
    payload: object
        phase1: 0
        phase2: 6
        phase3: 0
_msgid: "487fa53483d62d29"
``` 

Running version 0.6.0 in node-red v3.1.9 in docker

Any hints?

**Comment by runnane** [comment]
Hi @EskildPa 

Try adding a method POST and removing the topic like so:

```javascript
let l1 = 40;
let l2 = 40;
let l3 = 40;
msg.payload = {
    "path": "/sites/321/circuits/321/dynamicCurrent",
    "method": "POST",
    "body": {
        "phase1": l1,
        "phase2": l2,
        "phase3": l3,
    }
}

return msg;
```

**Comment by EskildPa** [comment]
Yes, this works. Thank you so much for this help, and thanks for publishing this module. Now I am looking forward to get further control of my easee.
