### ISSUE TITLE
can't use custom commands

### ISSUE THREAD

**Issue by rugnut** [runnane/node-red-contrib-easee#24]
I am trying to make custom commands work. Especially setting a charge plan but I have tried other commands as well. Custom commands for a GET without a body seems to work fine but I can not get any POST commands to work.

The only way I can make the REST Client node post is to use msg.method POST. Any other way it will try to make it a GET even though I include a body. 

It still fails the post with the error:
POST: failed : msg.payload : null
null

I have tried in many different ways but according to what I see in the docs and from the Easee API docs this looks the most correct. This is a function node to construct the msg to the REST Client:

msg.payload = {
    method: 'POST',
    path: '/chargers/XXXXXXXX/weekly_charge_plan',
    body: {
        "isEnabled": true,
        "days": [
            {
                "dayOfWeek": 0,
                "ranges": [
                    {
                        "chargingCurrentLimit": 32,
                        "startTime": "10:00",
                        "stopTime": "11:00"
                    }
                ]
            }
        ]
    }
};

return msg;

**Comment by runnane** [comment]
Hi @rugnut 
I guess this is bad documentation on my part - try wrapping the command inside msg.payload like this.
However - I see there also is a false error on return, so even if the command is excepted, it throws an error. This is fixed in release today, 

```javascript
msg.payload = {
    method: 'POST',
    path: '/chargers/EH00000/weekly_charge_plan',
    body: {
        "isEnabled": true,
        "days": [
            {
                "dayOfWeek": 0,
                "ranges": [
                    {
                        "chargingCurrentLimit": 32,
                        "startTime": "10:00",
                        "stopTime": "11:00"
                    }
                ]
            }
        ]
    }
};


return msg;
```

**Comment by rugnut** [comment]
Thanks! It works and I get no error with version 0.6.1.
