### ISSUE TITLE
Ability to set dynamic charge current.

### ISSUE THREAD

**Issue by iPeel** [runnane/node-red-contrib-easee#5]
For users with solar and / or battery storage it would be useful to set the dynamic charge current on a circuit, this would allow a Node-Red flow to monitor excess solar then apportion the available excess to a circuit to dump the excess into an EV rather than going out to export.

Easee provides an API for this: https://developer.easee.cloud/reference/post_api-sites-siteid-circuits-circuitid-dynamiccurrent

Note however the API is against a site and circuit combination and not on a charger, so might be better to add to a new node type of "Circuit" as opposed to the existing "Charger" node.

Thanks!

Neil.

**Comment by runnane** [comment]
Hi,

I have now updated the main node to be more "flexible".
You can now both pre-set variables for charger, site and circuit, or send them in as variables.
In addition, by using the custom command option (see the new readme) you can send about every command in the documentation if you know the endpoint and body set-up.

/Jon

**Comment by iPeel** [comment]
Brilliant, thanks Jon!

It looks like there's a typo in easee-rest-client.js with "stop_charging" entered twice in place of "start_charging". I'll add an issue. I also don't seem to be able to pause charging and get:

"/chargers/UKXXXX0YY/commands/pause_charging POST failed: Error: REST Command failed (400: Bad Request), check console for errors." and the Error label states "GET: Failed" which I assume should be "POST: Failed", I'll do some more testing on why that might be failing as I'm not currently charging.
