### ISSUE TITLE
What API Domain is the current version (v0.4.0) using?

### ISSUE THREAD

**Issue by KIDNORswe** [runnane/node-red-contrib-easee#7]
Hi, not an issue, more a question. I am wondering what API Doman the current version v0.4.0 is using please? Easee development is making changes to its API URL.  api.easee.cloud domain will close down September 1st 2023. New api.easee.com is running now.
 
Thank you

**Comment by runnane** [comment]
Hi,
signalR API is using the new endpoint. 
REST API is still using the old endpoint, it will be updated in the next publish.

/Jon
